import { Report, ModerationAction, Utilisateur } from '../models/index.js';
import { Op } from 'sequelize';

/**
 * Service de Modération Automatique
 * Génère des signalements automatiques basés sur les comportements suspects
 */

class AutoModerationService {
  
  /**
   * Créer un signalement automatique
   */
  async createAutoReport(reportData) {
    try {
      const {
        userId,
        type,
        reason,
        severity = 'medium',
        evidence = {},
        fileId = null
      } = reportData;

      // Vérifier si l'utilisateur existe
      const user = await Utilisateur.findByPk(userId);
      if (!user) {
        console.error(`❌ Utilisateur ${userId} non trouvé pour signalement automatique`);
        return null;
      }

      // Vérifier s'il n'y a pas déjà un signalement similaire récent
      const existingReport = await this.checkDuplicateReport(userId, type);
      if (existingReport) {
        console.log(`⚠️  Signalement similaire déjà existant pour ${userId}, type: ${type}`);
        return existingReport;
      }

      // Créer le signalement automatique
      const report = await Report.create({
        reporter_id: null, // Signalement système (pas d'utilisateur rapporteur)
        reported_user_id: userId,
        file_id: fileId,
        type: this.mapTypeToReportType(type),
        reason: reason,
        status: 'pending',
        source: 'automatic', // 🎯 CORRECTION : Marquer comme automatique
        evidence: JSON.stringify(evidence), // 📝 Ajouter les preuves
        admin_id: null,
        admin_action: null,
        resolved_at: null,
        metadata: {
          autoGenerated: true,
          systemType: type,
          severity: severity,
          evidence: evidence,
          generatedAt: new Date().toISOString(),
          riskScore: evidence.riskScore || 0
        }
      });

      console.log(`🤖 Signalement automatique créé: ${report.id} pour utilisateur ${userId}`);
      
      // Notifier l'admin selon la gravité
      await this.notifyAdmin(report, severity);
      
      // Prendre des actions automatiques si nécessaire
      await this.takeAutomaticActions(report, severity, evidence);

      return report;
    } catch (error) {
      console.error('❌ Erreur lors de la création du signalement automatique:', error);
      throw error;
    }
  }

  /**
   * Vérifier s'il existe déjà un signalement similaire récent
   */
  async checkDuplicateReport(userId, systemType) {
    try {
      const oneHourAgo = new Date(Date.now() - 60 * 60 * 1000);
      
      const existingReport = await Report.findOne({
        where: {
          reported_user_id: userId,
          status: 'pending',
          created_at: {
            [Op.gte]: oneHourAgo
          },
          metadata: {
            systemType: systemType
          }
        }
      });

      return existingReport;
    } catch (error) {
      console.error('❌ Erreur lors de la vérification des doublons:', error);
      return null;
    }
  }

  /**
   * Mapper les types système vers les types de signalement
   */
  mapTypeToReportType(systemType) {
    const typeMapping = {
      'system_upload_abuse': 'spam',
      'system_behavior_abuse': 'inappropriate',
      'system_api_abuse': 'spam',
      'system_critical_behavior': 'inappropriate',
      'system_suspicious_behavior': 'other',
      'system_security_risk': 'inappropriate'
    };

    return typeMapping[systemType] || 'other';
  }

  /**
   * Notifier l'administrateur selon la gravité
   */
  async notifyAdmin(report, severity) {
    try {
      // TODO: Implémenter les notifications (email, Slack, etc.)
      
      const notificationMessage = this.generateNotificationMessage(report, severity);
      
      console.log(`📧 Notification admin [${severity.toUpperCase()}]: ${notificationMessage}`);
      
      // En production, envoyer email/SMS/Slack selon la gravité
      if (severity === 'critical') {
        console.log('🚨 ALERTE CRITIQUE - Notification immédiate requise');
        // await this.sendCriticalAlert(report);
      } else if (severity === 'high') {
        console.log('⚠️  ALERTE ÉLEVÉE - Notification prioritaire');
        // await this.sendHighPriorityAlert(report);
      } else {
        console.log('📋 ALERTE STANDARD - Notification normale');
        // await this.sendStandardAlert(report);
      }
      
    } catch (error) {
      console.error('❌ Erreur lors de la notification admin:', error);
    }
  }

  /**
   * Générer le message de notification
   */
  generateNotificationMessage(report, severity) {
    const user = report.reported_user_id;
    const type = report.metadata?.systemType || 'unknown';
    const riskScore = report.metadata?.evidence?.riskScore || 0;
    
    return `Signalement automatique [${severity}]: Utilisateur ${user} - ${type} (Score: ${riskScore}/100)`;
  }

  /**
   * Prendre des actions automatiques selon la gravité
   */
  async takeAutomaticActions(report, severity, evidence) {
    try {
      const userId = report.reported_user_id;
      const riskScore = evidence.riskScore || 0;

      // Actions selon le score de risque
      if (riskScore >= 80) {
        // Score très critique : Suspension temporaire automatique
        await this.createAutoSuspension(userId, report.id, '24 heures', 'Score de risque critique (>80)');
        
      } else if (riskScore >= 60) {
        // Score élevé : Limitation sévère
        await this.createAutoWarning(userId, report.id, 'Comportement automatique détecté - Surveillance renforcée');
        
      } else if (riskScore >= 40) {
        // Score modéré : Avertissement automatique
        await this.createAutoWarning(userId, report.id, 'Activité suspecte détectée - Veuillez respecter les conditions d\'utilisation');
      }

      console.log(`⚙️  Actions automatiques appliquées pour utilisateur ${userId} (score: ${riskScore})`);
      
    } catch (error) {
      console.error('❌ Erreur lors des actions automatiques:', error);
    }
  }

  /**
   * Créer un avertissement automatique
   */
  async createAutoWarning(userId, reportId, reason) {
    try {
      // Trouver un admin système pour attribuer l'action
      const systemAdmin = await this.getSystemAdmin();
      
      const warning = await ModerationAction.create({
        user_id: userId,
        admin_id: systemAdmin.id,
        report_id: reportId,
        action_type: 'warning',
        reason: `[AUTOMATIQUE] ${reason}`,
        duration: null,
        start_date: new Date(),
        end_date: null,
        is_active: true,
        metadata: {
          autoGenerated: true,
          systemAction: true,
          generatedAt: new Date().toISOString()
        }
      });

      console.log(`⚠️  Avertissement automatique créé: ${warning.id} pour utilisateur ${userId}`);
      return warning;
      
    } catch (error) {
      console.error('❌ Erreur lors de la création de l\'avertissement automatique:', error);
      throw error;
    }
  }

  /**
   * Créer une suspension automatique
   */
  async createAutoSuspension(userId, reportId, duration, reason) {
    try {
      const systemAdmin = await this.getSystemAdmin();
      
      // Calculer la durée en jours
      const durationDays = this.parseDuration(duration);
      const endDate = new Date(Date.now() + durationDays * 24 * 60 * 60 * 1000);
      
      const suspension = await ModerationAction.create({
        user_id: userId,
        admin_id: systemAdmin.id,
        report_id: reportId,
        action_type: 'suspension',
        reason: `[AUTOMATIQUE] ${reason}`,
        duration: durationDays,
        start_date: new Date(),
        end_date: endDate,
        is_active: true,
        metadata: {
          autoGenerated: true,
          systemAction: true,
          generatedAt: new Date().toISOString(),
          originalDuration: duration
        }
      });

      console.log(`🚫 Suspension automatique créée: ${suspension.id} pour utilisateur ${userId} (${duration})`);
      return suspension;
      
    } catch (error) {
      console.error('❌ Erreur lors de la création de la suspension automatique:', error);
      throw error;
    }
  }

  /**
   * Obtenir l'admin système pour les actions automatiques
   */
  async getSystemAdmin() {
    try {
      // Chercher un admin système ou créer un compte système
      let systemAdmin = await Utilisateur.findOne({
        where: {
          email: 'system@hifadhui.site',
          role: 'admin'
        }
      });

      if (!systemAdmin) {
        // Créer un compte admin système si nécessaire
        systemAdmin = await Utilisateur.create({
          username: 'Système Hifadhui',
          email: 'system@hifadhui.site',
          password: 'system_account_no_login',
          role: 'admin',
          provider: 'system',
          metadata: {
            systemAccount: true,
            description: 'Compte système pour les actions automatiques'
          }
        });
        
        console.log('🤖 Compte admin système créé pour les actions automatiques');
      }

      return systemAdmin;
      
    } catch (error) {
      console.error('❌ Erreur lors de la récupération de l\'admin système:', error);
      throw error;
    }
  }

  /**
   * Parser la durée en jours
   */
  parseDuration(duration) {
    const durationMap = {
      '15 minutes': 0.01,
      '1 heure': 0.04,
      '6 heures': 0.25,
      '24 heures': 1,
      '3 jours': 3,
      '7 jours': 7,
      '14 jours': 14,
      '30 jours': 30
    };

    return durationMap[duration] || 1;
  }

  /**
   * Obtenir les statistiques des signalements automatiques
   */
  async getAutoReportStats(timeframe = '24h') {
    try {
      const timeframeDates = this.getTimeframeDate(timeframe);
      
      const stats = await Report.findAll({
        where: {
          created_at: {
            [Op.gte]: timeframeDates.start
          },
          metadata: {
            autoGenerated: true
          }
        },
        attributes: ['type', 'status', 'metadata'],
        raw: true
      });

      const summary = {
        total: stats.length,
        byType: {},
        byStatus: {},
        bySeverity: {},
        avgRiskScore: 0
      };

      let totalRiskScore = 0;
      let riskScoreCount = 0;

      stats.forEach(report => {
        // Par type
        summary.byType[report.type] = (summary.byType[report.type] || 0) + 1;
        
        // Par statut
        summary.byStatus[report.status] = (summary.byStatus[report.status] || 0) + 1;
        
        // Par gravité
        const severity = report.metadata?.severity || 'unknown';
        summary.bySeverity[severity] = (summary.bySeverity[severity] || 0) + 1;
        
        // Score de risque moyen
        const riskScore = report.metadata?.evidence?.riskScore;
        if (riskScore) {
          totalRiskScore += riskScore;
          riskScoreCount++;
        }
      });

      if (riskScoreCount > 0) {
        summary.avgRiskScore = Math.round(totalRiskScore / riskScoreCount);
      }

      return summary;
      
    } catch (error) {
      console.error('❌ Erreur lors de la récupération des stats:', error);
      throw error;
    }
  }

  /**
   * Obtenir la date de début selon la période
   */
  getTimeframeDate(timeframe) {
    const now = new Date();
    let start;

    switch (timeframe) {
      case '1h':
        start = new Date(now.getTime() - 60 * 60 * 1000);
        break;
      case '24h':
        start = new Date(now.getTime() - 24 * 60 * 60 * 1000);
        break;
      case '7d':
        start = new Date(now.getTime() - 7 * 24 * 60 * 60 * 1000);
        break;
      case '30d':
        start = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000);
        break;
      default:
        start = new Date(now.getTime() - 24 * 60 * 60 * 1000);
    }

    return { start, end: now };
  }

  /**
   * Résoudre automatiquement les anciens signalements
   */
  async resolveOldReports() {
    try {
      const sevenDaysAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
      
      // 1) Récupérer les signalements automatiques en attente créés il y a plus de 7 jours
      //    On évite de mettre un objet JSON complexe (avec tableau) dans where.metadata
      //    pour ne pas provoquer d'erreur Sequelize "Invalid value { autoGenerated: true }".
      const candidates = await Report.findAll({
        where: {
          status: 'pending',
          created_at: {
            [Op.lt]: sevenDaysAgo
          }
        },
        attributes: ['id', 'metadata']
      });

      // 2) Filtrer côté JS : uniquement les signalements automatiques
      //    avec une sévérité "low" ou "medium" dans metadata
      const targetIds = candidates
        .filter((report) => {
          const meta = report.metadata || {};
          const isAuto = meta.autoGenerated === true;
          const severity = meta.severity;
          return isAuto && (severity === 'low' || severity === 'medium');
        })
        .map((report) => report.id);

      if (targetIds.length === 0) {
        console.log('🧹 Aucun ancien signalement automatique à résoudre');
        return 0;
      }

      // 3) Mettre à jour uniquement les IDs filtrés
      const [updatedCount] = await Report.update(
        {
          status: 'resolved',
          admin_action: '[AUTOMATIQUE] Résolu automatiquement après 7 jours',
          resolved_at: new Date()
        },
        {
          where: {
            id: targetIds
          }
        }
      );

      console.log(`🧹 ${updatedCount} anciens signalements automatiques résolus`);
      return updatedCount;
      
    } catch (error) {
      console.error('❌ Erreur lors de la résolution automatique:', error);
      throw error;
    }
  }
}

// Créer une instance singleton
export const autoModerationService = new AutoModerationService();

// Programmer le nettoyage automatique (toutes les 6 heures)
setInterval(() => {
  autoModerationService.resolveOldReports().catch(console.error);
}, 6 * 60 * 60 * 1000);

export default autoModerationService;
